# Generated by Django 5.2.13 on 2026-04-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
                ('id', models.AutoField(db_column='idassinatura', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='assinatura', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'tblassinatura',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
                ('id', models.AutoField(db_column='idgenero', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='genero', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'db_table': 'tblgenero',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
                ('id', models.AutoField(db_column='idinstanciaocorrenciacaso', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='instancia', max_length=255, unique=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Instância',
                'verbose_name_plural': 'Instâncias',
                'db_table': 'tblinstanciaocorrenciacaso',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(db_column='idlivro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=255)),
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'tbllivro',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='LocalPublicacao',
            fields=[
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
                ('id', models.AutoField(db_column='idlocalpublicacao', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nomelocalpublicacao', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Local de publicação',
                'verbose_name_plural': 'Locais de publicação',
                'db_table': 'tbllocalpublicacao',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
                ('id', models.AutoField(db_column='idmidia', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='mdia', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'db_table': 'tblmidia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(db_column='idpeca', primary_key=True, serialize=False)),
                ('codigo_exibicao', models.CharField(blank=True, db_column='codigoexibicao', max_length=50)),
                ('nome_obra', models.CharField(db_column='nomedaobra', max_length=255)),
                ('nome_obra_simples', models.CharField(blank=True, db_column='nomedaobrasimples', max_length=255)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, db_column='anopublicacao', null=True)),
                ('mes_publicacao', models.PositiveSmallIntegerField(blank=True, db_column='mespublicacao', null=True)),
                ('data_publicacao', models.DateField(blank=True, db_column='datapublicacao', null=True)),
                ('fonte', models.TextField(blank=True)),
                ('dados_publicacao', models.TextField(blank=True, db_column='dadosdapublicacao')),
                ('observacoes', models.TextField(blank=True)),
                ('registro', models.TextField(blank=True)),
                ('reproducoes_texto', models.TextField(blank=True, db_column='reproducoes')),
                ('complemento_assinatura', models.CharField(blank=True, db_column='complementoassinatura', max_length=255)),
                ('numero_item', models.PositiveIntegerField(blank=True, db_column='numitem', null=True)),
                ('dia_assinatura', models.PositiveIntegerField(blank=True, db_column='diaassinatura', null=True)),
                ('mes_assinatura', models.PositiveSmallIntegerField(blank=True, db_column='mesassinatura', null=True)),
                ('ano_assinatura', models.PositiveIntegerField(blank=True, db_column='anoassinatura', null=True)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('trial446', models.CharField(blank=True, max_length=1, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(blank=True, db_column='idassinatura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.assinatura')),
                ('genero', models.ForeignKey(blank=True, db_column='idgenero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genero')),
                ('instancia', models.ForeignKey(blank=True, db_column='idinstancia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.instancia')),
                ('livro', models.ForeignKey(blank=True, db_column='idreuniaoemlivro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.livro')),
                ('local_publicacao', models.ForeignKey(blank=True, db_column='idlocalpub', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.localpublicacao')),
                ('midia', models.ForeignKey(blank=True, db_column='idmdia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.midia')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'db_table': 'tblpeca',
                'ordering': ['-ano_publicacao', 'nome_obra'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='tecnica', max_length=120)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('descricao', models.TextField(blank=True, db_column='observao')),
                ('trial449', models.CharField(blank=True, max_length=1, null=True)),
                ('peca', models.ForeignKey(db_column='idpeca', on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='catalog.peca')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
                'db_table': 'tbltecnicaassinatura',
            },
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['ano_publicacao'], name='tblpeca_anopubl_d85248_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['mes_publicacao'], name='tblpeca_mespubl_636cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['data_publicacao'], name='tblpeca_datapub_7ae98b_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['nome_obra'], name='tblpeca_nomedao_37493d_idx'),
        ),
    ]
