# Generated by Django 5.2.13 on 2026-04-15 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='codigo_exibicao',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='peca',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='url',
        ),
        migrations.AlterField(
            model_name='midia',
            name='nome',
            field=models.CharField(db_column='midia', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, db_column='datapublicacao', null=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='midia',
            field=models.ForeignKey(blank=True, db_column='idmidia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.midia'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='descricao',
            field=models.TextField(blank=True, db_column='observacao'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='id',
            field=models.AutoField(db_column='idtecnica', primary_key=True, serialize=False),
        ),
    ]
