# Generated by Django 5.2.13 on 2026-04-16 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_peca_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='codigo_exibicao',
            field=models.CharField(blank=True, db_column='codigoexibicao', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='mes_assinatura',
            field=models.PositiveSmallIntegerField(blank=True, db_column='mesassinatura', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='peca',
            name='mes_publicacao',
            field=models.PositiveSmallIntegerField(blank=True, db_column='mespublicacao', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['assinatura'], name='tblpeca_idassin_81d5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['genero'], name='tblpeca_idgener_c68a75_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['instancia'], name='tblpeca_idinsta_ea4843_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['livro'], name='tblpeca_idreuni_785f55_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['ano_publicacao', 'nome_obra'], name='idx_ano_obra'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['genero', 'ano_publicacao'], name='idx_genero_ano'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['assinatura', 'ano_publicacao'], name='idx_assinatura_ano'),
        ),
    ]
