# Generated by Django 5.2.13 on 2026-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_peca_codigo_exibicao_alter_peca_mes_assinatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='codigo_exibicao',
        ),
        migrations.AlterField(
            model_name='peca',
            name='mes_assinatura',
            field=models.PositiveSmallIntegerField(blank=True, db_column='mesassinatura', null=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='mes_publicacao',
            field=models.PositiveSmallIntegerField(blank=True, db_column='mespublicacao', null=True),
        ),
    ]
