# Generated by Django 5.2.13 on 2026-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_peca_codigo_exibicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='data_ordenacao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
