# Generated by Django 5.2.13 on 2026-04-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_data_ordenacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'ordering': ['-ano_publicacao', 'nome_obra'], 'verbose_name': 'Título', 'verbose_name_plural': 'Títulos'},
        ),
        migrations.CreateModel(
            name='ImagemPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pecas/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalog.peca')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
