# Generated by Django 5.2.13 on 2026-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_imagem_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genero',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='genero',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagempeca',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='imagempeca',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='instancia',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localpublicacao',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='localpublicacao',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midia',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='midia',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peca',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='peca',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencia',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='referencia',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
